// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactExcuses.Data;

namespace ReactExcuses.Data.Migrations
{
    [DbContext(typeof(ExcusesDbContext))]
    partial class ExcusesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReactExcuses.Data.ExcuseApiItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Excuse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Excuses");
                });

            modelBuilder.Entity("ReactExcuses.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReactExcuses.Data.UserLikedExcuses", b =>
                {
                    b.Property<int>("ExcuseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Liked")
                        .HasColumnType("bit");

                    b.HasKey("ExcuseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLikedExcuses");
                });

            modelBuilder.Entity("ReactExcuses.Data.UserLikedExcuses", b =>
                {
                    b.HasOne("ReactExcuses.Data.ExcuseApiItem", "Excuse")
                        .WithMany("UserLikedExcuses")
                        .HasForeignKey("ExcuseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReactExcuses.Data.User", "User")
                        .WithMany("UserLikedExcuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Excuse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactExcuses.Data.ExcuseApiItem", b =>
                {
                    b.Navigation("UserLikedExcuses");
                });

            modelBuilder.Entity("ReactExcuses.Data.User", b =>
                {
                    b.Navigation("UserLikedExcuses");
                });
#pragma warning restore 612, 618
        }
    }
}
